import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../store/farm_store.dart';

class EmployeesScreen extends StatelessWidget {
  const EmployeesScreen({super.key});
  @override Widget build(BuildContext context) { final store = context.watch<FarmStore>(); return _Page(title: store.t('الموظفون والرواتب', 'Employees & payroll'), action: FilledButton.icon(onPressed: () => _addEmployee(context), icon: const Icon(Icons.person_add), label: Text(store.t('إضافة موظف', 'Add employee'))), child: Column(children: [Card(child: ListTile(leading: const Icon(Icons.payments, color: Colors.green), title: Text(store.t('إجمالي صافي الرواتب', 'Total net payroll')), trailing: Text('${store.payroll.toStringAsFixed(0)} ج.م', style: const TextStyle(fontWeight: FontWeight.bold)))), const SizedBox(height: 12), Expanded(child: ListView.separated(itemCount: store.employees.length, separatorBuilder: (_, __) => const Divider(), itemBuilder: (_, i) { final e = store.employees[i]; return ListTile(leading: CircleAvatar(child: Text(e.name.substring(0, 1))), title: Text(e.name), subtitle: Text('${e.phone} • ${store.t('الراتب', 'Salary')}: ${e.salary.toStringAsFixed(0)}'), trailing: Text('${e.netSalary.toStringAsFixed(0)} ج.م')); }))])); }
  Future<void> _addEmployee(BuildContext context) async { final store = context.read<FarmStore>(); final name = TextEditingController(), phone = TextEditingController(), salary = TextEditingController(); await showDialog(context: context, builder: (_) => AlertDialog(title: Text(store.t('إضافة موظف', 'Add employee')), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: InputDecoration(labelText: store.t('الاسم', 'Name'))), TextField(controller: phone, decoration: InputDecoration(labelText: store.t('الهاتف', 'Phone'))), TextField(controller: salary, keyboardType: TextInputType.number, decoration: InputDecoration(labelText: store.t('الراتب', 'Salary')))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: Text(store.t('إلغاء', 'Cancel'))), FilledButton(onPressed: () { final value = double.tryParse(salary.text); if (name.text.isNotEmpty && value != null) store.addEmployee(Employee(id: DateTime.now().toString(), name: name.text, phone: phone.text, salary: value)); Navigator.pop(context); }, child: Text(store.t('حفظ', 'Save'))])); }
}

class InventoryScreen extends StatelessWidget { const InventoryScreen({super.key}); @override Widget build(BuildContext context) { final store = context.watch<FarmStore>(); return _Page(title: store.t('المخزون والصوبة الزراعية', 'Inventory & nursery'), action: FilledButton.icon(onPressed: () => _add(context), icon: const Icon(Icons.add), label: Text(store.t('إضافة صنف', 'Add item'))), child: ListView.separated(itemCount: store.stock.length, separatorBuilder: (_, __) => const Divider(), itemBuilder: (_, i) { final x = store.stock[i]; return ListTile(leading: const Icon(Icons.inventory_2_outlined), title: Text(x.name), subtitle: Text(x.category), trailing: Text('${x.quantity.toStringAsFixed(0)} ${x.unit}', style: const TextStyle(fontWeight: FontWeight.bold))); })); }
  Future<void> _add(BuildContext context) async { final store = context.read<FarmStore>(); final name = TextEditingController(), category = TextEditingController(), quantity = TextEditingController(), unit = TextEditingController(); await showDialog(context: context, builder: (_) => AlertDialog(title: Text(store.t('إضافة صنف', 'Add item')), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: InputDecoration(labelText: store.t('اسم الصنف', 'Item name'))), TextField(controller: category, decoration: InputDecoration(labelText: store.t('التصنيف', 'Category'))), TextField(controller: quantity, keyboardType: TextInputType.number, decoration: InputDecoration(labelText: store.t('الكمية', 'Quantity'))), TextField(controller: unit, decoration: InputDecoration(labelText: store.t('الوحدة', 'Unit')))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: Text(store.t('إلغاء', 'Cancel'))), FilledButton(onPressed: () { final q = double.tryParse(quantity.text); if (name.text.isNotEmpty && q != null) store.addStock(StockItem(id: DateTime.now().toString(), name: name.text, category: category.text, quantity: q, unit: unit.text)); Navigator.pop(context); }, child: Text(store.t('حفظ', 'Save')))])); }
}

class ReportsScreen extends StatelessWidget { const ReportsScreen({super.key}); @override Widget build(BuildContext context) { final store = context.watch<FarmStore>(); return _Page(title: store.t('التقارير والتحليلات', 'Reports & analytics'), child: ListView(children: [Card(child: ListTile(leading: const Icon(Icons.calendar_month), title: Text(store.t('تقرير الشهر الحالي', 'Current month report')), subtitle: Text(store.t('صافي الربح والخسارة والحركة المالية', 'Profit, loss and financial activity')), trailing: FilledButton(onPressed: () {}, child: Text(store.t('عرض', 'View'))))), Card(child: Column(children: [ListTile(title: Text(store.t('ملخص الحسابات', 'Accounts summary')), trailing: Text('${store.transactions.length}')), const Divider(), _row(store.t('الإيرادات', 'Income'), store.income, Colors.green), _row(store.t('المصروفات', 'Expenses'), store.expenses, Colors.orange), _row(store.t('الرصيد', 'Balance'), store.balance, Colors.blue)])), const SizedBox(height: 12), OutlinedButton.icon(onPressed: () {}, icon: const Icon(Icons.picture_as_pdf), label: Text(store.t('تصدير PDF (قريباً)', 'Export PDF (coming soon)')))])); }
  Widget _row(String label, double value, Color color) => ListTile(title: Text(label), trailing: Text('${value.toStringAsFixed(0)} ج.م', style: TextStyle(color: color, fontWeight: FontWeight.bold)));
}

class _Page extends StatelessWidget { const _Page({required this.title, required this.child, this.action}); final String title; final Widget child; final Widget? action; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(title, style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.bold))), if (action != null) action!]), const SizedBox(height: 20), Expanded(child: child)]); }
